### ISSUE TITLE
Use CSS Selectors

### ISSUE THREAD

**Issue by dziper** [dziper/fa22-cse110-lab3#6]
## Task Description: 

- [ ] Class Selector
- [ ] ID Selector
- [ ] Universal Selector
- [ ] Element Selector
- [ ] Attribute Selector
- [ ] Psuedo-class Selector
- [ ] Selector List
- [ ] Combinators
  - [ ] Descendant Combinator
  - [ ] Child Combinator
  - [ ] General sibling combinator
  - [ ] Adjacent sibling combinator
  - [ ] Combining Two selectors 

## Estimated Time:
2hr
